<nav>
	<div class="logo"><a href="index.php"><img class="logo" src="images/logo.png" alt="Logo" title="Back to Homepage" /></a></div>
		<p class="menu"><a href="index.php">Home</a></p>
		<p class="menu"><a href="product.php">Product</a> </p>
		<p class="menu"><a href="enquire.php">Enquiry</a></p>
		<p class="menu"><a href="about.php">About</a></p>
		<p class="menu"><a href="enhancements3.php">Enhancements</a></p>
		<p class="menu"><a href="manager.php">Manager</a></p>
</nav>